apiVersion: v1
kind: Secret
metadata:
  name: paperpulse-secret
  namespace: paperpulse
  labels:
    app.kubernetes.io/name: paperpulse
    app.kubernetes.io/component: secret
type: Opaque
stringData:
  # These values should be replaced with actual base64 encoded values
  # Use: echo -n 'your-value' | base64
  APP_KEY: "base64:YOUR_APP_KEY_HERE"
  DB_USERNAME: "paperpulse"
  DB_PASSWORD: "changeme"
  REDIS_PASSWORD: "changeme"
  MEILISEARCH_KEY: "changeme"
  AWS_ACCESS_KEY_ID: "your-aws-key"
  AWS_SECRET_ACCESS_KEY: "your-aws-secret"
  AWS_BUCKET: "your-s3-bucket"
  OPENAI_API_KEY: "your-openai-key"
  MAIL_HOST: "smtp.example.com"
  MAIL_PORT: "587"
  MAIL_USERNAME: "your-mail-username"
  MAIL_PASSWORD: "your-mail-password"
  MAIL_ENCRYPTION: "tls"