apiVersion: apps/v1
kind: Deployment
metadata:
  name: paperpulse-web
  namespace: paperpulse
  labels:
    app.kubernetes.io/name: paperpulse
    app.kubernetes.io/component: web
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: paperpulse
      app.kubernetes.io/component: web
  template:
    metadata:
      labels:
        app.kubernetes.io/name: paperpulse
        app.kubernetes.io/component: web
    spec:
      initContainers:
      - name: migrations
        image: paperpulse/web:latest
        imagePullPolicy: Always
        command: ["php", "artisan", "migrate:safe", "--force"]
        envFrom:
        - configMapRef:
            name: paperpulse-config
        - secretRef:
            name: paperpulse-secret
      containers:
      - name: web
        image: paperpulse/web:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: paperpulse-config
        - secretRef:
            name: paperpulse-secret
        livenessProbe:
          httpGet:
            path: /up
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /up
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        volumeMounts:
        - name: storage
          mountPath: /app/storage
        - name: cache
          mountPath: /app/bootstrap/cache
      volumes:
      - name: storage
        emptyDir: {}
      - name: cache
        emptyDir: {}