user www-data;
worker_processes auto;
pid /tmp/nginx.pid;
error_log /dev/stderr;
events { worker_connections 1024; }
http {
    include /etc/nginx/mime.types;
    access_log /dev/stdout;
    client_max_body_size 110m;
    server {
        listen 3900;
        server_name _;
        location / {
            proxy_set_header Host $http_host;
            proxy_pass http://garage:3900;
            proxy_request_buffering off;
        }
    }
    server {
        listen 80 default_server;
        server_name _;
        root /app/public;
        index index.php;
        location / { try_files $uri $uri/ /index.php?$query_string; }
        location ~ \.php$ {
            include fastcgi_params;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            fastcgi_pass 127.0.0.1:9002;
        }
        location ~ /\. { deny all; }
    }
}
